name: CI Pipeline Desafio Keegoo
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Rodar testes Cypress em modo headless
      - name: Run Cypress tests
        run: npx cypress run
